### ISSUE TITLE
Create Infra validation tests Stage Install [CM]

### ISSUE THREAD

**Issue by esilvaju** [WLCG-Lightweight-Sites/simple_grid_infra_validation_engine#1]
### Check if the /etc/simple_grid dir was created 
stage: install, node: config_master, component: None
### Check if git was installed\
stage: install, node: config_master, component: None
### Check if docker was installed
stage: install, node: config_master, component: None
### Check if bolt was installed
run the command: rpm -qa|grep bolt
```
puppet-bolt-1.28.0-1.el7.x86_64
bolt-0.4-3.el7.x86_64
```
stage: install, node: config_master, component: None

**Comment by snehasi** [comment]
Hey,

Should the script terminate with a raised exception in case tests for Git, Docker and bolt install fail?

**Comment by snehasi** [comment]
Hey @ejr004 

> run the command: rpm -qa|grep bolt
> 
> ```
> puppet-bolt-1.28.0-1.el7.x86_64
> bolt-0.4-3.el7.x86_64
> ```
> 
> stage: install, node: config_master, component: None


I think bolt isn't installed on the docker image, only puppet-bolt is installed right now

**Comment by snehasi** [comment]
Resolved by #9
